name: Merge Imgbot

on:
  pull_request:
    types:
      - opened
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
       - name: merge a pull request
         uses: sudo-bot/action-pull-request-merge@v1.1.1
         with:
           github-token: ${{ secrets.GIT_MERGE_TOKEN }}
           number: ${{ github.event.pull_request.number }}
           allowed-usernames-regex: ^[ImgBot]
           filter-label: merge-it
       
